/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursemanagementsystem;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Mustafa
 */
public class AdminWorkplace extends javax.swing.JFrame {

    public AdminWorkplace(String title) {
        super(title);
        ImageIcon icon = new ImageIcon("iconsmall.png");
        setIconImage(icon.getImage());
        setLocationRelativeTo(null);
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        welcomeTxt = new javax.swing.JLabel();
        BoxPanel = new javax.swing.JPanel();
        EntityComboBox = new javax.swing.JComboBox<>();
        CRUDComboBox = new javax.swing.JComboBox<>();
        SumbitButton = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("workplace"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 768));
        setResizable(false);

        welcomePanel.setBackground(new java.awt.Color(0, 0, 0));

        welcomeTxt.setBackground(new java.awt.Color(255, 255, 255));
        welcomeTxt.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        welcomeTxt.setForeground(new java.awt.Color(255, 255, 255));
        welcomeTxt.setText("Course Management System                                                                                                                                               Workplace");

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        BoxPanel.setBackground(new java.awt.Color(204, 204, 204));

        EntityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty", "Course", "Student" }));
        EntityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntityComboBoxActionPerformed(evt);
            }
        });

        CRUDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CREATE", "READ", "UPDATE", "DELETE" }));
        CRUDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDComboBoxActionPerformed(evt);
            }
        });

        SumbitButton.setText("Confirm");
        SumbitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumbitButtonActionPerformed(evt);
            }
        });

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursemanagementsystem/University.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BoxPanelLayout = new javax.swing.GroupLayout(BoxPanel);
        BoxPanel.setLayout(BoxPanelLayout);
        BoxPanelLayout.setHorizontalGroup(
            BoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BoxPanelLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addGroup(BoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon)
                    .addGroup(BoxPanelLayout.createSequentialGroup()
                        .addGroup(BoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CRUDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EntityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(156, 156, 156))
                    .addGroup(BoxPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SumbitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BoxPanelLayout.setVerticalGroup(
            BoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EntityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CRUDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SumbitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntityComboBoxActionPerformed

    private void CRUDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CRUDComboBoxActionPerformed

    private void SumbitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumbitButtonActionPerformed

        Object entitySelectedItem = EntityComboBox.getModel().getSelectedItem();
        boolean isStudent = entitySelectedItem.equals("Student");
        boolean isFaculty = entitySelectedItem.equals("Faculty");
        boolean isCourse = entitySelectedItem.equals("Course");

        Object CRUDSelectedItem = CRUDComboBox.getModel().getSelectedItem();
        boolean isCreate = CRUDSelectedItem.equals("CREATE");
        boolean isRead = CRUDSelectedItem.equals("READ");
        boolean isUpdate = CRUDSelectedItem.equals("UPDATE");
        boolean isDelete = CRUDSelectedItem.equals("DELETE");

        if (isStudent) {

            System.out.println("Student is selected");
            CRUDpackage.CRUDFrame frame = new CRUDpackage.Student();
            if (isCreate) {
                System.out.println("CREATE is selected");
                frame.createFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });
            } else if (isRead) {
                System.out.println("READ is selected.");
                frame.readFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });
            } else if (isUpdate) {
                System.out.println("UPDATE is selected.");
            } else if (isDelete) {
                System.out.println("DELETE is selected.");
            }

        } else if (isFaculty) {

            System.out.println("Faculty is SELECTED");
            CRUDpackage.CRUDFrame frame = new CRUDpackage.Faculty();
            if (isCreate) {;
                System.out.println("CREATE is selected");
                frame.createFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });

            } else if (isRead) {
                System.out.println("READ is selected.");
                frame.readFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });
            } else if (isUpdate) {
                System.out.println("UPDATE is selected.");
                frame.updateFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });
            } else if (isDelete) {
                System.out.println("DELETE is selected.");
                frame.deleteFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });
            }
        } else if (isCourse) {
            System.out.println("Course is selected.");

            CRUDpackage.CRUDFrame frame = new CRUDpackage.Course();

            if (isCreate) {
                System.out.println("CREATE is selected");
                frame.createFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });
            } else if (isRead) {
                System.out.println("READ is selected.");
                frame.readFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });
            } else if (isUpdate) {
                System.out.println("UPDATE is selected.");
                frame.updateFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });
            } else if (isDelete) {
                System.out.println("DELETE is selected.");
                frame.deleteFrame();
                java.awt.EventQueue.invokeLater(() -> {
                    frame.setVisible(true);
                });
            }
        }
    }//GEN-LAST:event_SumbitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoxPanel;
    private javax.swing.JComboBox<String> CRUDComboBox;
    private javax.swing.JComboBox<String> EntityComboBox;
    private javax.swing.JButton SumbitButton;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JLabel welcomeTxt;
    // End of variables declaration//GEN-END:variables

}
